### ISSUE TITLE
pybump command not found

### ISSUE THREAD

**Issue by slumbang129** [ArieLevs/PyBump#8]
Hi There, 

I tried running pybump command in my local and it works fine.  However when I try it on my docker image it's not able to find the command.  It says `pybump command not found`.  Here's what's on my Jenkinsfile

[Pipeline] sh
+ pip --version
pip 19.3.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

[Pipeline] sh
+ pybump --version
.../script.sh: pybump: not found

**Comment by ArieLevs** [comment]
Hi,

As i understand you are using this app inside a container, It seems you are using the `python:2.7` image,
you will need to use python 3.6+, i'd recommend the `python:3.7-alpine` image.

please note that pybump does not exists by default in these containers.
you will need to install pybump (`pip install pybump`) or create your own image, for example:
```
FROM python:3.7-alpine

RUN pip install --upgrade pip
RUN pip install pybump

RUN python --version
```

Please let me know it helped, or if you are still facing issues, thanks.

**Comment by ArieLevs** [comment]
@slumbang129 was the issue resolved
